### ISSUE TITLE
Crash when trying to parse MH4U .pcapng file

### ISSUE THREAD

**Issue by GrenderG** [PretendoNetwork/nex-viewer#17]
![image](https://github.com/PretendoNetwork/nex-viewer/assets/8654362/346c4aa4-5f58-4c9c-9bf3-c10b292cd541)

Let me know if you need more information.

**Comment by jonbarrow** [comment]
I believe I know why this happens, there's a fix in the mentioned PR which should solve this. I'll leave this open, though, just in case that's not the underlying cause after all

**Comment by jonbarrow** [comment]
This should be fixed now
